FROM jenkins/jenkins:lts

USER root

ARG DOCKER_GID

RUN apt-get update && \
    apt-get install -y \
        git \
        curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Create a group matching the host Docker socket GID
RUN groupadd -g ${DOCKER_GID} docker-host && \
    usermod -aG docker-host jenkins

USER jenkins

COPY plugins.txt /usr/share/jenkins/ref/plugins.txt

RUN jenkins-plugin-cli --plugin-file /usr/share/jenkins/ref/plugins.txt
